### ISSUE TITLE
Need to use Retrofit httpclient as a main requests handler

### ISSUE THREAD

**Issue by ishikawayoshi** [runtep/simpleweather#2]
We can you use this http client to handle requests
http://square.github.io/retrofit/, what do you think about it?

**Comment by runtep** [comment]
It's a great idea. Seems like the lib can perform all necessary job.
I've prepared a draft version: perform search by name and display results.
Please take a look at **city_search** branch

**Comment by runtep** [comment]
Task completed: all client request have been rewritten based on "Retrofit"
