### ISSUE TITLE
Improve weather display

### ISSUE THREAD

**Issue by di72nn** [runtep/simpleweather#7]
Emphasize important information like day temperature.

Also, it would be great to shorten descriptive text.

**Comment by runtep** [comment]
Implemented in branch
[https://github.com/runtep/simpleweather/tree/feature/emphasize_temp](url)

Screen example
![screenshot_1547544895](https://user-images.githubusercontent.com/581300/51171459-69437600-18ca-11e9-8e14-0915500c5cbe.png)
